### ISSUE TITLE
Podcast "the memory palace" fails to update

### ISSUE THREAD

**Issue by virtualbri** [podStation/podStation#341] opened 2022-11-28 16:21 UTC
The iTunes podcast "the memory palace" fails to update on podStation.  This same feed works fine on other podcast programs, so there might be something underlying issue in podStation.   I don't get any other feedback but the grey box "the memory palace has failed to update" and sometimes it shows as properly subscribed to, and sometimes I get an RSS logo and http://feeds.thememorypalace.us/thememorypalace with an undefined link (image attached)

Current Chrome is Version 107.0.5304.122 (Official Build) (64-bit) but this has persisted over several builds.  

<img width="818" alt="28 11 2022_08 18 09_REC" src="https://user-images.githubusercontent.com/85041913/204328276-4ca4513b-d1b7-4656-862d-7393a3d7ffa7.png">
<img width="809" alt="28 11 2022_08 20 50_REC" src="https://user-images.githubusercontent.com/85041913/204328504-8bffba64-48c2-4790-862b-7a566f447c4a.png">

**Comment by dellagustin** [comment] 2022-12-12 21:28
Hello @virtualbri , I have just added it on my installation of podStation. It worked fine for the moment, I'll check from time to time to see if I can reproduce the issue.

**Comment by dellagustin** [comment] 2023-01-04 21:25
Hello @virtualbri , I could not reproduce this issue. Is it still happening for you?
I'll close the issue for now. If you are still facing it, please reopen it.

**Closed by dellagustin** 2023-01-04 21:25 UTC
Labels: can't reproduce
